"""Map between agent prompt components and GEPA candidates."""

from __future__ import annotations

from collections.abc import Iterator, Sequence
from contextlib import ExitStack, contextmanager
from typing import TYPE_CHECKING, Any

from pydantic import BaseModel
from pydantic_ai.agent.wrapper import WrapperAgent

from .signature import InputSpec, build_input_spec
from .signature_agent import SignatureAgent
from .tool_components import get_tool_optimizer

if TYPE_CHECKING:
    from pydantic_ai.agent import AbstractAgent


def _strip_surrogate_characters(text: str) -> str:
    """Remove stray UTF-16 surrogate code points to keep text JSON-safe.

    Args:
        text: Raw text that may include half-surrogates generated by providers.

    Returns:
        The same text with surrogate code points removed.

    Examples:
        >>> _strip_surrogate_characters("Valid\\ud800")
        'Valid'
    """
    # Filter out lone surrogate characters that cause UTF-8 encoding failures.
    return "".join(char for char in text if not 0xD800 <= ord(char) <= 0xDFFF)


def normalize_component_text(value: Any) -> str:
    """Normalize prompt component values to safe string representations.

    Args:
        value: A prompt component value (string, list, tuple, etc.).

    Returns:
        A UTF-8-safe string suitable for GEPA serialization.

    Examples:
        >>> normalize_component_text(["Step 1", "Step 2"])
        'Step 1\\n\\nStep 2'
    """
    if value is None:
        return ""
    if isinstance(value, str):
        return _strip_surrogate_characters(value)
    if isinstance(value, Sequence) and not isinstance(value, (str, bytes)):
        # Join multi-part components with blank lines to preserve readability.
        joined = "\n\n".join(str(part) for part in value if part)
        return _strip_surrogate_characters(joined)
    # Fallback to string conversion, then sanitize surrogate code points.
    return _strip_surrogate_characters(str(value))


def extract_seed_candidate(agent: AbstractAgent[Any, Any]) -> dict[str, str]:
    """Extract the current prompts from an agent as a GEPA candidate.

    Args:
        agent: The agent to extract prompts from.

    Returns:
        A dictionary mapping component names to their text values.
        - 'instructions': The effective instructions (combining literal and functions)
    """
    candidate: dict[str, str] = {}

    target_agent = agent
    if isinstance(agent, WrapperAgent):
        target_agent = agent.wrapped

    # Extract instructions
    # Note: In v1, we extract the literal instructions only, not the dynamic ones
    # The dynamic instructions from functions will be disabled during optimization
    if hasattr(target_agent, "_instructions") and target_agent._instructions:  # type: ignore[attr-defined]
        candidate["instructions"] = normalize_component_text(
            target_agent._instructions  # type: ignore[attr-defined]
        )
    else:
        candidate["instructions"] = ""

    if isinstance(agent, SignatureAgent):
        if agent.optimize_tools:
            candidate.update(agent.get_tool_components())
    else:
        optimizer = get_tool_optimizer(agent)
        if optimizer:
            candidate.update(optimizer.get_seed_components())

    return candidate


@contextmanager
def apply_candidate_to_agent(
    agent: AbstractAgent[Any, Any],
    candidate: dict[str, str] | None,
) -> Iterator[None]:
    """Apply a GEPA candidate to an agent via override().

    This returns a context manager that temporarily applies the candidate
    prompts to the agent.

    Args:
        agent: The agent to apply prompts to.
        candidate: The candidate mapping component names to text.

    Returns:
        A context manager for the temporary override.
    """
    instructions_raw = candidate.get("instructions") if candidate else None
    instructions = (
        normalize_component_text(instructions_raw) if instructions_raw else None
    )

    target_agent = agent
    if isinstance(agent, WrapperAgent):
        target_agent = agent.wrapped

    optimizer = get_tool_optimizer(agent)

    with ExitStack() as stack:
        if optimizer:
            stack.enter_context(optimizer.candidate_context(candidate))
        if instructions:
            stack.enter_context(target_agent.override(instructions=instructions))
        yield


def get_component_names(agent: AbstractAgent[Any, Any]) -> list[str]:
    """Get the list of optimizable component names for an agent.

    Args:
        agent: The agent to inspect.

    Returns:
        List of component names that can be optimized.
    """
    components: list[str] = ["instructions"]

    optimizer = get_tool_optimizer(agent)
    if isinstance(agent, SignatureAgent) and not agent.optimize_tools:
        optimizer = None

    if optimizer:
        components.extend(optimizer.get_component_keys())

    # Preserve order but ensure uniqueness
    seen: set[str] = set()
    deduped: list[str] = []
    for component in components:
        if component not in seen:
            deduped.append(component)
            seen.add(component)

    return deduped


def validate_components(
    agent: AbstractAgent[Any, Any], components: Sequence[str]
) -> list[str]:
    """Validate that the requested components exist in the agent.

    Args:
        agent: The agent to check against.
        components: The requested component names.

    Returns:
        The validated list of component names.

    Raises:
        ValueError: If any component doesn't exist in the agent.
    """
    available = set(get_component_names(agent))
    requested = set(components)

    invalid = requested - available
    if invalid:
        raise ValueError(
            f"Components {invalid} not found in agent. Available components: {sorted(available)}"
        )

    return list(components)


def extract_seed_candidate_with_signature(
    agent: AbstractAgent[Any, Any],
    input_type: InputSpec[BaseModel] | None = None,
) -> dict[str, str]:
    """Extract initial prompts from an agent and optionally a signature as a GEPA candidate.

    Args:
        agent: The agent to extract prompts from.
        input_type: Optional structured input specification to extract from.

    Returns:
        Combined dictionary of all components and their initial text.
    """
    candidate: dict[str, str] = {}

    # Extract from agent
    candidate.update(extract_seed_candidate(agent))

    # Extract from signature if provided
    if input_type:
        spec = build_input_spec(input_type)
        candidate.update(spec.get_gepa_components())

    return candidate


@contextmanager
def apply_candidate_to_agent_and_signature(
    candidate: dict[str, str] | None,
    agent: AbstractAgent[Any, Any],
    input_type: InputSpec[BaseModel] | None = None,
) -> Iterator[None]:
    """Apply a GEPA candidate to an agent and optionally a signature.

    This context manager temporarily applies the candidate to the agent
    (via override()) and optionally to a signature class.

    Args:
        candidate: The candidate mapping component names to text.
        agent: The agent to apply prompts to.
        input_type: Optional structured input specification to apply to.

    Yields:
        None while the candidate is applied.
    """
    from contextlib import ExitStack

    with ExitStack() as stack:
        # Apply to agent
        stack.enter_context(apply_candidate_to_agent(agent, candidate))

        # Apply to signature if provided
        if input_type:
            spec = build_input_spec(input_type)
            stack.enter_context(spec.apply_candidate(candidate))

        yield
